version: "3"
services:
  nginx:
    build: ./nginx-dev
    image: gmontag/nginx:nginx-dev
    links:
      - node
    ports:
      - "80:80"
      - "3000:3000"
      - "4000:4000"
      - "443:443"
    volumes:
      - /usr/local/etc/nginx/psw:/etc/nginx/psw
      - /usr/local/etc/nginx/ssl:/etc/nginx/ssl
    environment:
      - DOMAIN_NAME=localhost
    networks:
      - web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
  node:
    build: ./Dockerfile-dev
    image: gmontag/node:node-dev
    links:
      - mongo
    volumes:
      - ./compiled:/compiled
    env_file:
      - ./node.env
    environment:
      - SERVER_PORT=3001
      - NODE_ENV=development
    networks:
      - web
      - server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.6"
          memory: 600M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
  swagger:
    build: ./swagger
    image: gmontag/swagger:swagger
    links:
      - node
    volumes:
      - ./swagger/public:/swagger/public
    environment:
      - SERVER_PORT=4001
      - NODE_ENV=development
    networks:
      - web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
  mongo:
    image: mongo
    networks:
      - server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
networks:
  web:
  server:
