version: "3"
services:
  nginx:
    build: ./nginx-dev
    image: gmontag/nginx:nginx-dev
    links:
      - node
    ports:
      - "80:80"
      - "3000:3000"
      - "443:443"
    networks:
      - web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  node:
    build: ./Dockerfile-dev
    image: gmontag/node:node-dev
    links:
      - mongo
    env_file:
      - ./node.env
    environment:
      - SERVER_PORT=3001
      - NODE_ENV=development
    ports:
      - "5858:5858"
    networks:
      - web
      - server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.7"
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 2
        delay: 10s
  swagger:
    build: ./swagger
    image: gmontag/swagger:swagger
    volumes:
      - ./swagger/public:/swagger
    ports:
      - "3001:3001"
    networks:
      - web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 2
        delay: 10s
  mongo:
    image: mongo
    volumes:
      - /Users/arthur/data/db/:/data/db
    networks:
      - server
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 3
networks:
  web:
  server:
