FROM node:6

# Create app directory
# RUN apt-get update && \
#     apt-get -y install curl

RUN mkdir -p /home/node/compiled
RUN mkdir -p /home/node/uploads
ADD ./index.js /home/node/index.js

# Provides cached layer for node_modules
ADD ./package.json /tmp/package.json
RUN cd /tmp && npm install
RUN cp -a /tmp/node_modules /home/node

# Define working directory
ADD ./compiled /home/node/compiled
WORKDIR /home/node

USER node

CMD ["node", "./index.js"]
