version: "3"
services:
  nginx:
    build: ./nginx-prod
    image: gmontag/nginx:nginx-prod
    links:
      - node
    ports:
      - "80:80"
      - "443:443"
    domainname: domain.com
    networks:
      - web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
  node:
    build: ./Dockerfile-prod
    image: gmontag/node:node-prod
    links:
      - mongo
    env_file:
      - ./node.env
    environment:
      - SERVER_PORT=3001
      - NODE_ENV=production
    networks:
      - web
      - server
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
  mongo:
    image: mongo
    networks:
      - server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
networks:
  web:
  server:
