FROM node:6

# Create app directory
# RUN apt-get update && \
#     apt-get -y install curl

RUN mkdir -p /src/compiled
RUN mkdir -p /src/uploads
ADD ./index.js /src/index.js

# Provides cached layer for node_modules
ADD ./src/package.json /tmp/package.json
RUN cd /tmp && npm install
RUN cp -a /tmp/node_modules /src

RUN npm i nodemon -g

# Define working directory
VOLUME ./compiled /src/compiled
WORKDIR /src

USER node

CMD ["nodemon", "-L", "--delay", "2", "--ext", "js", "--debug=5858", "./index.js"]
