FROM node:6

MAINTAINER Arthur Osipenko

# Create app directory
# RUN apt-get update && \
#     apt-get -y install curl

RUN mkdir -p /src/compiled
RUN mkdir -p /src/uploads
ADD ./index.js /src/index.js

# Provides cached layer for node_modules
ADD ./package.json /tmp/package.json
RUN cd /tmp && npm install
RUN cp -a /tmp/node_modules /src

# Define working directory
ADD ./compiled /src/compiled
WORKDIR /src

USER node

CMD ["node", "./index.js"]
